version: '3.8'

services:
  jenkins:
    build: .
    restart: always
    privileged: true
    user: root
    ports:
      - ${JENKENS_PORT}:${JENKENS_PORT}
      - 50000:50000
    container_name: jenkins
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./jenkins.yaml:/var/jenkins_home/casc_configs/jenkins.yaml
    environment:
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=${JENKENS_runSetupWizard}
      - CASC_JENKINS_CONFIG=/var/jenkins_home/casc_configs
    networks:
      - jenkins

networks:
  jenkins:
    
